[functions]
  directory = "dist"
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"                  
  to = "/.netlify/functions/:splat"  
  status = 200
  force = true